version: '3'
services:
  web:
    container_name: craft_web_punditmedia
    image: craftcms/craft:latest
    volumes:
      - ./:/app:cached
    ports:
      - 3860:80
    environment:
      ENVIRONMENT: dev
      SECURITY_KEY: 0a6ef32d-14c2-404f-8999-57e3dc04ceda
      DB_DRIVER: mysql
      DB_SERVER: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: craft_punditmedia
      DB_PORT: 3306
    depends_on:
      - mysql
  mysql:
    container_name: craft_mysql_punditmedia
    restart: always
    image: mysql:5.7
    ports:
      - 3870:3306 
    environment:
      MYSQL_DATABASE: craft_punditmedia
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - craft_mysql_punditmedia:/var/lib/mysql

volumes:
  craft_mysql_punditmedia:
